server:
  port: 8080

jwt:
  secret: "JPBXkgSltOTzTiOGLoxvJUS9qbg8Lj7MGcOdvU4hclg="

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/your_database_name
#    username: your_username
#    password: your_password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true